#!/usr/bin/env ruby
# encoding: UTF-8
require './lib/web_page_fetcher'

class Fetch
  def self.parse(args)
    metadata_mode = args.include?('--metadata')
    urls = args.reject { |arg| arg == '--metadata' }
    new(urls, metadata_mode)
  end

  private

  attr_reader :urls, :metadata_mode

  def initialize(urls, metadata_mode)
    @urls = urls
    @metadata_mode = metadata_mode
  end

  public

  def run
    if @urls.empty?
      puts 'Usage: ./fetch url1 url2 [...]'
      exit(1)
    end

    fetcher = WebPageFetcher.new(@urls, @metadata_mode)
    fetcher.process_urls
  end
end

Fetch.parse(ARGV).run
